// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQIiLwiXnOfXj7_DeDzQgD0GVA553RPl4',
    appId: '1:83066154674:android:6418c43941e789dbcaa3ab',
    messagingSenderId: '83066154674',
    projectId: 'mylibraryappsbloc',
    storageBucket: 'mylibraryappsbloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh9C3LOZHMXTLvjIjCiDLZFefPpMxSuMY',
    appId: '1:83066154674:ios:e1e6ed6968290aefcaa3ab',
    messagingSenderId: '83066154674',
    projectId: 'mylibraryappsbloc',
    storageBucket: 'mylibraryappsbloc.appspot.com',
    androidClientId: '83066154674-hvfvinssdu0agvevt0t3h8oj1vgj536b.apps.googleusercontent.com',
    iosClientId: '83066154674-ul7vv4os34dbvuu5636pbbnpm44pl20a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mylibraryapps',
  );
}
